version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgresql-synapsis
    environment:
      DATABASE_URL: postgres://user:password@postgresql-synapsis:5432/mydatabase

  postgresql-synapsis:
    image: postgres:latest
    environment:
      POSTGRES_USER: rendy
      POSTGRES_PASSWORD: rendy
      POSTGRES_DB: rendy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
